export default {
    profile: {},
    userProfile: [],
    newQuotations: [],
    token: '',
    comentQuotations: [],
    comentEmotions: [],
    myQuotations: [],
    allEmotions: [],
    about: [],
    aboutID: {},
    allMyQuotations: [],
    allMyQuotationsCreate: [],
    allMyQuotationsCreateByID: {},
    idEmotion: '',
    search: [],
    type: '',
    detailOrder: [],
    idBooking: '',
    searchKey: '',
    backgroundPage: {},
    tags: [],
    emotionTagRealte: [],
    getOrderBookingSearch: [],
    saveQuotationAuthor: '',
}